owner: Tediware
repo: tediware-upptime

sites:
  - name: Tediware
    url: https://tediware.com/

assignees:
  - adriand

status-website:
  cname: status.tediware.com
  name: Tediware Status
  introTitle: "**Tediware** uptime monitor and status page."
  introMessage: Real-time uptime and response-time data for tediware.com, powered by [Upptime](https://upptime.js.org).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
